import {
  LayoutDashboard,
  Users,
  CalendarClock,
  Ruler,
  Image as ImageIcon,
  ShoppingBag,
  Box,
  FileText,
  Receipt,
  CreditCard,
  Truck,
  Wallet,
  Star,
  Settings,
  Inbox,
  Palette,
  TrendingUp,
  MessageSquare,
} from "lucide-react";
import type { NavItem } from "@/types/nav";

// Grouped for readability only (see NavItem.group) — every item, href, and
// order is unchanged from before; nothing was removed or hidden. A flat
// list of 19 items with no structure was itself the usability problem.
export const NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard, implemented: true },
  { label: "Messages", href: "/dashboard/messages", icon: MessageSquare, implemented: true, description: "Direct conversations with your customers." },

  {
    label: "Customers",
    href: "/dashboard/customers",
    icon: Users,
    implemented: true,
    description: "Manage customer profiles, preferences, and history.",
    group: "Customers",
  },
  {
    label: "Service Requests",
    href: "/dashboard/service-requests",
    icon: Inbox,
    implemented: true,
    description: "Requests from customers discovering you on Fashion360.",
    group: "Customers",
  },
  {
    label: "Appointments",
    href: "/dashboard/appointments",
    icon: CalendarClock,
    implemented: true,
    description: "Book and track consultations, fittings, and pickups.",
    group: "Customers",
  },
  {
    label: "Measurements",
    href: "/dashboard/measurements",
    icon: Ruler,
    implemented: true,
    description: "Manual and AI-assisted body measurement profiles.",
    group: "Customers",
  },
  {
    label: "Customer Measurements",
    href: "/dashboard/customer-measurements",
    icon: Ruler,
    implemented: true,
    description: "Customers who've granted access to their platform Measurement Vault.",
    group: "Customers",
  },

  {
    label: "Design Projects",
    href: "/dashboard/design-projects",
    icon: Palette,
    implemented: true,
    description: "Collaborate with customers from design brief through approval.",
    group: "Design & Production",
  },
  {
    label: "Design Gallery",
    href: "/dashboard/design-gallery",
    icon: ImageIcon,
    implemented: true,
    description: "Browse and curate your digital design catalogue.",
    group: "Design & Production",
  },
  {
    label: "3D Studio",
    href: "/dashboard/3d-studio",
    icon: Box,
    implemented: true,
    description: "Interactive garment visualization and customization.",
    group: "Design & Production",
  },
  {
    label: "Orders",
    href: "/dashboard/orders",
    icon: ShoppingBag,
    implemented: true,
    description: "Track custom orders through your production workflow.",
    group: "Design & Production",
  },
  {
    label: "Delivery",
    href: "/dashboard/delivery",
    icon: Truck,
    implemented: true,
    description: "Manage pickup and home delivery logistics.",
    group: "Design & Production",
  },

  {
    label: "Quotations",
    href: "/dashboard/quotations",
    icon: FileText,
    implemented: true,
    description: "Create and send price quotes to customers.",
    group: "Money",
  },
  {
    label: "Invoices",
    href: "/dashboard/invoices",
    icon: Receipt,
    implemented: true,
    description: "Generate invoices and track payment status.",
    group: "Money",
  },
  {
    label: "Payments",
    href: "/dashboard/payments",
    icon: CreditCard,
    implemented: true,
    description: "Deposits, balances, and payment history.",
    group: "Money",
  },
  {
    label: "Payouts",
    href: "/dashboard/payouts",
    icon: Wallet,
    implemented: true,
    description: "Track payout eligibility for your completed orders.",
    group: "Money",
  },

  {
    label: "Reviews",
    href: "/dashboard/reviews",
    icon: Star,
    implemented: true,
    description: "Customer ratings and finished-look photos.",
    group: "Grow",
  },
  {
    label: "Insights",
    href: "/dashboard/insights",
    icon: TrendingUp,
    implemented: true,
    description: "How customers discover and engage with your business.",
    group: "Grow",
  },

  { label: "Settings", href: "/dashboard/settings", icon: Settings, implemented: true },
];
