import {
  LayoutDashboard,
  Users,
  CalendarClock,
  Ruler,
  Image as ImageIcon,
  ShoppingBag,
  Box,
  FileText,
  Receipt,
  CreditCard,
  Truck,
  Star,
  Gift,
  BarChart3,
  Settings,
} from "lucide-react";
import type { NavItem } from "@/types/nav";

export const NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard, implemented: true },
  {
    label: "Customers",
    href: "/dashboard/customers",
    icon: Users,
    implemented: false,
    description: "Manage customer profiles, preferences, and history.",
  },
  {
    label: "Appointments",
    href: "/dashboard/appointments",
    icon: CalendarClock,
    implemented: false,
    description: "Book and track consultations, fittings, and pickups.",
  },
  {
    label: "Measurements",
    href: "/dashboard/measurements",
    icon: Ruler,
    implemented: false,
    description: "Manual and AI-assisted body measurement profiles.",
  },
  {
    label: "Design Gallery",
    href: "/dashboard/design-gallery",
    icon: ImageIcon,
    implemented: false,
    description: "Browse and curate your digital design catalogue.",
  },
  {
    label: "Orders",
    href: "/dashboard/orders",
    icon: ShoppingBag,
    implemented: false,
    description: "Track custom orders through your production workflow.",
  },
  {
    label: "3D Studio",
    href: "/dashboard/3d-studio",
    icon: Box,
    implemented: false,
    description: "Interactive garment visualization and customization.",
  },
  {
    label: "Quotations",
    href: "/dashboard/quotations",
    icon: FileText,
    implemented: false,
    description: "Create and send price quotes to customers.",
  },
  {
    label: "Invoices",
    href: "/dashboard/invoices",
    icon: Receipt,
    implemented: false,
    description: "Generate invoices and track payment status.",
  },
  {
    label: "Payments",
    href: "/dashboard/payments",
    icon: CreditCard,
    implemented: false,
    description: "Deposits, balances, and payment history.",
  },
  {
    label: "Delivery",
    href: "/dashboard/delivery",
    icon: Truck,
    implemented: false,
    description: "Manage pickup and home delivery logistics.",
  },
  {
    label: "Reviews",
    href: "/dashboard/reviews",
    icon: Star,
    implemented: false,
    description: "Customer ratings and finished-look photos.",
  },
  {
    label: "Loyalty",
    href: "/dashboard/loyalty",
    icon: Gift,
    implemented: false,
    description: "Reward points, referrals, and coupons.",
  },
  {
    label: "Reports",
    href: "/dashboard/reports",
    icon: BarChart3,
    implemented: false,
    description: "Revenue, growth, and performance analytics.",
  },
  { label: "Settings", href: "/dashboard/settings", icon: Settings, implemented: true },
];
