import { Document, Page, Text, View } from "@react-pdf/renderer";
import { pdfStyles as s } from "./styles";
import { formatCurrency, formatDate } from "@/lib/utils";

export function InvoicePdf({
  businessName,
  currency,
  invoice,
}: {
  businessName: string;
  currency: string;
  invoice: {
    invoiceNumber: string;
    status: string;
    amount: string;
    amountPaid: string;
    dueDate: string | null;
    createdAt: string;
    customer: { name: string; email: string | null; phone: string | null };
    payments: Array<{ type: string; amount: string; createdAt: string; status: string }>;
  };
}) {
  const balance = Number(invoice.amount) - Number(invoice.amountPaid);

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.businessName}>{businessName}</Text>
            <Text style={s.muted}>Invoice</Text>
          </View>
          <View>
            <Text style={s.docTitle}>{invoice.invoiceNumber}</Text>
            <Text style={s.muted}>{formatDate(invoice.createdAt)}</Text>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.label}>Billed to</Text>
          <Text>{invoice.customer.name}</Text>
          {invoice.customer.email && <Text style={s.muted}>{invoice.customer.email}</Text>}
          {invoice.customer.phone && <Text style={s.muted}>{invoice.customer.phone}</Text>}
        </View>

        <View style={s.table}>
          <View style={s.tableRow}>
            <Text style={s.tableCellLeft}>Invoice amount</Text>
            <Text style={s.tableCellRight}>{formatCurrency(invoice.amount, currency)}</Text>
          </View>
          <View style={s.tableRow}>
            <Text style={s.tableCellLeft}>Amount paid</Text>
            <Text style={s.tableCellRight}>{formatCurrency(invoice.amountPaid, currency)}</Text>
          </View>
          <View style={s.tableRow}>
            <Text style={s.tableCellLeft}>Balance due</Text>
            <Text style={s.tableCellRight}>{formatCurrency(balance, currency)}</Text>
          </View>
        </View>

        {invoice.payments.length > 0 && (
          <View style={s.section}>
            <Text style={s.label}>Payment history</Text>
            {invoice.payments.map((p, i) => (
              <View key={i} style={s.row}>
                <Text style={s.muted}>
                  {formatDate(p.createdAt)} — {p.type}
                </Text>
                <Text>{formatCurrency(p.amount, currency)}</Text>
              </View>
            ))}
          </View>
        )}

        {invoice.dueDate && (
          <View style={s.section}>
            <Text style={s.label}>Due date</Text>
            <Text>{formatDate(invoice.dueDate)}</Text>
          </View>
        )}

        <Text style={s.footer}>Generated by Fashion360 — {businessName}</Text>
      </Page>
    </Document>
  );
}
