import { Document, Page, Text, View } from "@react-pdf/renderer";
import { pdfStyles as s } from "./styles";
import { formatCurrency, formatDate } from "@/lib/utils";

export function QuotationPdf({
  businessName,
  currency,
  quotation,
}: {
  businessName: string;
  currency: string;
  quotation: {
    quoteNumber: string;
    status: string;
    description: string;
    price: string;
    deposit: string;
    balance: string;
    dueDate: string | null;
    createdAt: string;
    customer: { name: string; email: string | null; phone: string | null };
  };
}) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.businessName}>{businessName}</Text>
            <Text style={s.muted}>Quotation</Text>
          </View>
          <View>
            <Text style={s.docTitle}>{quotation.quoteNumber}</Text>
            <Text style={s.muted}>{formatDate(quotation.createdAt)}</Text>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.label}>Prepared for</Text>
          <Text>{quotation.customer.name}</Text>
          {quotation.customer.email && <Text style={s.muted}>{quotation.customer.email}</Text>}
          {quotation.customer.phone && <Text style={s.muted}>{quotation.customer.phone}</Text>}
        </View>

        <View style={s.section}>
          <Text style={s.label}>Description</Text>
          <Text>{quotation.description}</Text>
        </View>

        <View style={s.table}>
          <View style={s.tableRow}>
            <Text style={s.tableCellLeft}>Total price</Text>
            <Text style={s.tableCellRight}>{formatCurrency(quotation.price, currency)}</Text>
          </View>
          <View style={s.tableRow}>
            <Text style={s.tableCellLeft}>Deposit required</Text>
            <Text style={s.tableCellRight}>{formatCurrency(quotation.deposit, currency)}</Text>
          </View>
          <View style={s.tableRow}>
            <Text style={s.tableCellLeft}>Balance</Text>
            <Text style={s.tableCellRight}>{formatCurrency(quotation.balance, currency)}</Text>
          </View>
        </View>

        {quotation.dueDate && (
          <View style={s.section}>
            <Text style={s.label}>Due date</Text>
            <Text>{formatDate(quotation.dueDate)}</Text>
          </View>
        )}

        <Text style={s.footer}>Generated by Fashion360 — {businessName}</Text>
      </Page>
    </Document>
  );
}
